sonar.projectKey=lab-ci-api
sonar.projectName=LabCI-CD
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,coverage/**,.git/**
sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info